### ISSUE TITLE
vagrant up issue

### ISSUE THREAD

**Issue by pradeepkumartangudu** [oneops/setup#20] opened 2016-03-09 11:47 UTC
Hi Team,
Below error we running vagrant up command..
could you please help me

---

System Details:

---

WINDOWS 8.1
RAM 8GB
vagrant_1.8.1
VirtualBox-5.0.16-105871-Win
# 
# ERROR INFO

$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/centos-6.7' could not be found. Attempting to find and i
nstall...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'bento/centos-6.7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/bento/centos-6.7"]
Error:

**Comment by kfilipovski** [comment] 2016-03-17 20:22
@pradeepkumartangudu do you still have this issue?  can you access that url https://atlas.hashicorp.com/bento/centos-6.7 in your browser ok?  you can try using the vagrant-centos7 directory which uses a different virtualbox image as an alternative, but if you have problems accessing the hashicorp site to get the base image the setup won't work.

**Comment by pradeepkumartangudu** [comment] 2016-03-19 13:47
![errror_vagrant](https://cloud.githubusercontent.com/assets/8360958/13898920/207f277a-ee07-11e5-9b26-68c6c6c7cd0a.PNG)

**Comment by pradeepkumartangudu** [comment] 2016-03-19 13:48
Still we are facing the same issue with 7 too,able to access through browser but unable do this from script.

**Comment by nimkar** [comment] 2016-03-21 16:49
It seems you are behind a corporate firewall which is using a proxy to allow access to internet. Hence you are able to access through your browser but command is failing via the command line. You can manually download the box through here https://atlas.hashicorp.com/bento/boxes/centos-6.7/versions/2.2.3/providers/virtualbox.box and then add it to the vagrant cache by running the command
vagrant box add --name "bento/centos-6.7" file:///full/path/to/the/virtualbox.box

Let us know how that works out.

**Comment by RAMESHBABU18** [comment] 2016-03-22 12:47
Hi Team,
We changed our network setting it is working fine,
But organization is not creating in oneops UI. could you please help as

**Comment by pradeepkumartangudu** [comment] 2016-03-22 12:55
Hi,
Ya, vagrant up is completed. after changed our corporate firewall proxy setting.

**Below Errors**: 
==> default: OO install cassandra 2.1.12
==> default: http://www.us.apache.org/dist/cassandra/2.1.12/apache-cassandra-2.1
.12-bin.tar.gz:
==> default: 2016-03-21 11:11:56 ERROR 404: Not Found.
==> default: env:
==> default: /etc/init.d/tomcat7
==> default: : No such file or director
  ==> default: env:
==> default: /etc/init.d/cassandra
==> default: : No such file or directory
==> default: Error: Unable to access jarfile /home/oneops/build/build-wf/war/WEB
-INF/jenkins-cli.jar
  ==> default: ERROR: knife encountered an unexpected error 
 ==> default: pgrep: invalid option -- 'a'
==> default: Usage: pgrep [-flvx] [-d DELIM]
==> default: [-n|-o] [-P PPIDLIST] [-g PGRPLIST] [-s SIDLIST]
==> default:    [-u EUIDLIST] [-U UIDLIST] [-G GIDLIST] [-t TERMLIST] [PATTERN]
==> default: env:
==> default: /etc/init.d/display
==> default: : No such file or directory

But we are facing issue with origination creating fails in the Oneops  UI.

**Comment by nimkar** [comment] 2016-03-24 17:09
Does your OneOps box have access to the cassandra site ? Now it seems it cannot access apache website. In general, OneOps downloads all dependencies from the internet during setup. Your box will need access to the internet during this time.

**Comment by RAMESHBABU18** [comment] 2016-03-28 12:41
ya we have access to the cassandra site as well as apache site

**Comment by pavel-sakun** [comment] 2017-01-07 20:51
Same issue with centos/7. Might me caused by changed atlas structure. URL from error message is "https://atlas.hashicorp.com/centos/7" and curl shows the following:
❯❯❯ curl -I https://atlas.hashicorp.com/centos/7                                                 ⏎
HTTP/1.1 301 Moved Permanently
Cache-Control: no-cache
Content-Length: 108
Content-Type: text/html
Date: Sat, 07 Jan 2017 20:50:23 GMT
Location: https://atlas.hashicorp.com/centos/boxes/7
Just a guess though.

**Comment by pavel-sakun** [comment] 2017-01-09 13:08
Resolved by updating vagrant to 1.9.1

**Comment by Ilhicas** [comment] 2017-01-17 15:38
@pavel-sakun that seems to be unrelated.

Have the same issue here with bento/centos-7.2 and running under vagrant 1.9.1

**Comment by aminor00** [comment] 2017-02-02 18:00
@pavel-sakun Thanks, upgrading to Vagrant 1.9.1 on MacOS 10.12 (Sierra) also worked for me.

Repeated runs with 1.8.7 did not work.  Simply installing 1.9.1 and trying again fixed it.

My "curl" also returned the "moved permanently" message.

**Closed** 2017-03-03 21:50 UTC

**Comment by someshkusampudi** [comment] 2018-02-09 03:46
hi i am unable to do vagrant up

the steps i followed are 
vagrant init centos/7
vagrant up
the error is as follows.....
vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'centos/7' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'centos/7' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/centos/7"]
Error: The requested URL returned error: 404 Not Found



the vagrant version--1.8.4
virtualbox----5.0.32
windows 7 os 64 bit


can anybody help me. plz its very urgent.
Thanks inadvance

**Comment by mosabua** [comment] 2018-02-09 04:36
PLease use the new process as described on the website with the main oneops repo.

**Comment by someshkusampudi** [comment] 2018-02-09 05:39
I am very much thankful to your reply  mosabua,  can you let me know the url where i can find the solution please. i am new to this process.

**Comment by mosabua** [comment] 2018-02-09 05:46
http://oneops.com/developer/core-development/index.html

**Comment by someshkusampudi** [comment] 2018-02-09 05:55
Thanks mosabua, but i am working on windows7, sorry to say that i didn,t find the probable solution for windows

**Comment by someshkusampudi** [comment] 2018-02-09 05:56
i am able to do for **vagrant init ubuntu/trusty64**
but for other boxes i am unable to do it

**Comment by mosabua** [comment] 2018-02-09 07:25
yes .. old process no longer works. And old or new .. windows never worked for the build. You need to be on osx or linux
